modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory 
# issueTrackerURL="http://my.issue.tracker/" #option
logoFile="logo.png" #optional

[[mods]] #mandatory
	modId="tutorialmod" #mandatory
	version="${file.jarVersion}" #mandatory
	displayName="Tutorial Mod" #mandatory
	# displayURL="http://example.com/" #optional
	# updateJSONURL="http://myurl.me/" #optional
	credits="Thanks To Drieeeeeeeeeeeemel." #optional
	authors="HackerMeiser SunFlow" #optional	
	
	description='''
    This is a simple Mod.
    To learn Minecraft Modding
    EZ PZ
    '''

[[dependencies.tutorialmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"